
import { VideoTranscript, TranscriptSegment } from '../types';

export const fetchYouTubeTranscript = async (videoId: string): Promise<VideoTranscript> => {
  try {
    // Use our backend API for transcript generation
    const response = await fetch(`http://localhost:3001/api/transcript/${videoId}`);
    
    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.message || `HTTP ${response.status}: ${response.statusText}`);
    }
    
    const data = await response.json();
    
    return {
      segments: data.segments,
      language: data.language || 'en',
      isAutoGenerated: data.isAutoGenerated || false,
      totalDuration: data.totalDuration // Real duration from Whisper
    };
  } catch (error) {
    console.error('Backend transcript fetch error:', error);
    throw new Error(`Failed to fetch transcript: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
};


export const validateTranscript = (transcript: VideoTranscript): boolean => {
  // TODO: Validate transcript quality and completeness
  if (!transcript || !transcript.segments || transcript.segments.length === 0) {
    return false;
  }

  // Check if transcript has reasonable coverage (segments span most of the video)
  const totalDuration = transcript.segments.reduce((total, segment) => 
    total + segment.duration, 0
  );
  
  // Require at least 30 seconds of transcript content
  return totalDuration >= 30;
};