export type AppScreen = 'input' | 'processing' | 'player' | 'explore';

export interface VideoData {
  id: string;
  title: string;
  duration: number;
  url: string;
  thumbnailUrl?: string;
}

export interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

export interface HighlightInterval {
  id: string;
  name: string;
  startTime: number;
  endTime: number;
  reason: string;
}

export interface HighlightSegment {
  id: string;
  title: string;
  startTime: number;
  endTime: number;
  type: 'hook' | 'explanation' | 'demo' | 'tip' | 'conclusion';
}

export interface ProcessingStatus {
  stage: 'validating' | 'fetching_transcript' | 'ai_analysis' | 'complete';
  progress: number;
  message: string;
}

export interface VideoTranscript {
  segments: TranscriptSegment[];
  language: string;
  isAutoGenerated: boolean;
  totalDuration?: number; // Real duration from Whisper transcription
}

export interface AppState {
  currentScreen: AppScreen;
  inputUrl: string;
  videoData: VideoData | null;
  transcript: VideoTranscript | null;
  highlights: HighlightSegment[];
  highlightIntervals: HighlightInterval[];
  processing: ProcessingStatus | null;
  currentHighlight: string | null;
  isPlaying: boolean;
  currentTime: number;
}